### PR TITLE
THaEvt125Handler.C missing from src/SConscript.py

### PR DESCRIPTION
**Pull request by sawjlab**
We should figure out how to avoid duplication of class names in SConscript.py and src/SConscript.py

### CODE REVIEW

**Comment by brash99** [comment]
Are you saying that you would prefer that it not be necessary to add the header file for the class to SConscript.py and the source file to src/SConscript.py?  I can make it so that it is only necessary to add the class name in one place, if that is what is desired.

**Comment by sawjlab** [comment]
I would think it would be desirable not to have to maintain multiple lists of the classes, at least within one build system.  Even nicer would be not having to also maintain that list in he LinkDef files, although there could be some subtleties there.

**Comment by brash99** [comment]
I'll work on the first part of that.  Shouldn't be too difficult.

**Comment by brash99** [comment]
I've made some progress on this and can talk about it at the next meeting.  I basically have it all working now, but want to discuss a couple of philosophical points before making commits.

**Pull request merged**
